version: '3.7'
services:
  web:
    image: nginx:latest
    build: .docker/nginx
    container_name: dev-nginx-polymer
    restart: unless-stopped
    ports:
      - 8000:80
      - 444:443
    volumes:
      - ./:/var/www/html/polymer/:ro
    depends_on:
      - php
      - db

  db:
    image: mariadb:latest
    container_name: dev-mariadb-polymer
    volumes:
      - .docker/data/db:/var/lib/mariadb/data:rw
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_USER: 'root'
      MARIADB_DATABASE: 'polymer'
      MARIADB_HOST: 'localhost'
    ports:
      - 3307:3306

  php:
    build: .docker/php
    container_name: dev-php-polymer
    volumes:
      - ./:/var/www/html/polymer:rw,cached
    depends_on:
      - db
