controllers:
  resource: ../src/Controller/Api
  type: annotation
  prefix: api
  name_prefix: api_
  defaults:
    _format: json


app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login_check:
  path: /api/auth/login_check

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
